#pragma once

#define NACK_LIST_MAX_SIZE 250
#define NACK_PKT_MAX_AGE 450
#define SR_RR_INERVAL 1000
#define REMB_INTERVAL 1000
#define NACK_PROCESS_INERVAL 10
#define RTT_INERVAL 10
#define RTP_SESSION_TIMEOUT 3000
#define RTP_SESSION_MAX_TIMEOUT 10000
#define RTP_CNAME "laifeng.com"
#define MAX_NACK_BITRATE 1 << 23
#define ENABLE_SUGGEST_PKT_INTERVAL 0
#define IS_CALC_LOST_WITH_RETRANS 1
#define ENABLE_INNER_JETTERBUF 0
#define MAX_RECONNECT_SECONDS  3600*24*7 //one week
#define MIN_SAME_NACK_INTERVAL 30
#define FEC_RTP_COUNT 4
#define FEC_INTERLEAVE_PACKAGE_VAL 2
